In [2]:
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np 

importa o dataset e divide ele em variavel de teste e variavel de treino 

In [3]:
(X_train,y_train),(X_test, y_test) = keras.datasets.mnist.load_data()

retorna quanto elementos tem na variavel 

In [ ]:
len(X_train)

In [ ]:
len(X_test)

Retorna a dimenção do elemento 

In [ ]:
X_train[0].shape

retorna 1 o elemento em formato(desenho) de array, onde 0 é preto e 2.. é branco 

In [ ]:
X_train[0]

mostra o elemento em um grafo usano matplotlib

In [ ]:
plt.matshow(X_train[2])

Retorna a label 

In [ ]:
y_train[2]

In [ ]:
y_train[:5]

divide as variaveis por 255 para redmencionalas: utilizando a função do pandas reshape trasformamos os elementos bidimensionais 28x28 em elementos unidimensionais 784

In [4]:
X_train = X_train/255
X_test = X_test/ 255

In [ ]:
X_train[0]

In [5]:
X_train_flattened = X_train.reshape(len(X_train),28*28)
X_test_flattened = X_test.reshape(len(X_test),28*28)
X_train_flattened.shape


(60000, 784)

In [ ]:
X_test_flattened.shape

In [ ]:
X_train_flattened[0]

. Dense: todo neoronio se conecta com a proxima camada
. sequencial:toda leyer tem um elemento 
.(output,input,activation)
. optimizer:treinar mais eficiente
.loss:output é categorico 0-9
.fit: treinar 
.epochs:quantas vezes vai treinar 

In [6]:
model= keras.Sequential([
    keras.layers.Dense(10,input_shape=(784,),activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)
    
model.fit(X_train_flattened,y_train,epochs=30)


Epoch 1/30
1875/1875 [==============================] - 2s 1ms/step - loss: 0.4681 - accuracy: 0.8767
Epoch 2/30
1875/1875 [==============================] - 2s 1ms/step - loss: 0.3031 - accuracy: 0.9154
Epoch 3/30
1875/1875 [==============================] - 2s 1ms/step - loss: 0.2827 - accuracy: 0.9211
Epoch 4/30
1875/1875 [==============================] - 2s 1ms/step - loss: 0.2731 - accuracy: 0.9232
Epoch 5/30
1875/1875 [==============================] - 2s 1ms/step - loss: 0.2662 - accuracy: 0.9257
Epoch 6/30
1875/1875 [==============================] - 2s 1ms/step - loss: 0.2618 - accuracy: 0.9276
Epoch 7/30
1875/1875 [==============================] - 2s 1ms/step - loss: 0.2581 - accuracy: 0.9285
Epoch 8/30
1875/1875 [==============================] - 2s 1ms/step - loss: 0.2556 - accuracy: 0.9299
Epoch 9/30
1875/1875 [==============================] - 3s 1ms/step - loss: 0.2531 - accuracy: 0.9301
Epoch 10/30
1875/1875 [==============================] - 2s 1ms/step - loss: 0.250

In [7]:
model.evaluate(X_test_flattened, y_test)

313/313 [==============================] - 0s 929us/step - loss: 0.2796 - accuracy: 0.9256


[0.2796210050582886, 0.925599992275238]

In [ ]:
plt.matshow(X_test[0])

In [8]:
model.predict(X_test_flattened)

313/313 [==============================] - 0s 804us/step


array([[3.3144712e-05, 2.9766016e-11, 3.8599703e-04, ..., 9.9989271e-01,
        1.0034354e-01, 6.4122689e-01],
       [6.2863939e-02, 2.6139750e-03, 9.9970514e-01, ..., 4.4155103e-21,
        3.7213136e-02, 7.0166769e-19],
       [4.3995482e-05, 9.9590129e-01, 6.8668610e-01, ..., 1.2923934e-03,
        3.1474519e-01, 3.0084208e-02],
       ...,
       [1.9151273e-07, 2.2243249e-08, 1.8325960e-04, ..., 1.1523402e-01,
        6.9958395e-01, 6.5097100e-01],
       [1.9885555e-07, 5.4561355e-07, 4.1683595e-07, ..., 3.8044698e-06,
        6.5782839e-01, 2.8212662e-07],
       [1.6510296e-05, 1.2136325e-13, 3.9114814e-02, ..., 3.5567894e-18,
        2.7485729e-07, 3.1252329e-12]], dtype=float32)

In [9]:
y_predicted= model.predict(X_test_flattened)
y_predicted[1]

313/313 [==============================] - 0s 754us/step


array([6.2863939e-02, 2.6139750e-03, 9.9970514e-01, 2.6339968e-03,
       1.8153075e-14, 7.8489798e-01, 9.3377930e-01, 4.4155103e-21,
       3.7213136e-02, 7.0166769e-19], dtype=float32)

In [10]:
np.argmax(y_predicted[1])

2

In [11]:
y_predicted_labels = [np.argmax(i) for  i in y_predicted]
y_predicted_labels[:5]

[7, 2, 1, 0, 4]

In [12]:
y_test[:5]

array([7, 2, 1, 0, 4], dtype=uint8)

In [13]:
cm = tf.math.confusion_matrix(labels=y_test, predictions=y_predicted_labels)
cm

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[ 956,    0,    0,    2,    1,    7,   10,    3,    1,    0],
       [   0, 1107,    3,    2,    0,    1,    4,    2,   16,    0],
       [   6,    8,  907,   23,    7,    3,   13,    9,   52,    4],
       [   3,    0,   11,  927,    0,   21,    3,   10,   28,    7],
       [   1,    1,    5,    3,  913,    0,   11,    5,   10,   33],
       [  10,    3,    1,   40,    7,  763,   15,    9,   41,    3],
       [  10,    3,    7,    2,    7,   10,  916,    1,    2,    0],
       [   1,    6,   23,    6,    4,    1,    0,  953,    5,   29],
       [   7,    5,    4,   18,    7,   16,    9,    7,  896,    5],
       [   9,    7,    1,   10,   19,    6,    0,   25,   14,  918]])>

In [ ]:
import seaborn as sn
plt.figure(figsize = (10,7))
sn.heatmap(cm, annot=True, fmt='d')
plt.xlabel('Predicted')
plt.ylabel('Truth')

In [ ]:
model= keras.Sequential([
    keras.layers.Dense(100,input_shape=(784,),activation='relu')
     keras.layers.Dense(10,activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)
    
model.fit(X_train_flattened,y_train,epochs=10)

In [ ]:
model.evaluate(X_test_flattened, y_test)

In [ ]:
import seaborn as sn
plt.figure(figsize = (10,7))
sn.heatmap(cm, annot=True, fmt='d')
plt.xlabel('Predicted')
plt.ylabel('Truth')

In [ ]:
model= keras.Sequential([
    karas.layers.Flatten(input_shape=(28,28))
    keras.layers.Dense(100,activation='relu')
     keras.layers.Dense(10,activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)
    
model.fit(X_train,y_train,epochs=10)